### ISSUE TITLE
Изменить файл инициализации БД

### ISSUE THREAD

**Issue by Wilddangerousbee** [outsidious/del-meetups#4]
В приложение роли пишутся в верхнем регистре: "USER", "ADMIN". В базу данных при инициализации они заносятся в нижнем, чтобы все роуты отрабатывали корректно нужно исправить инициализацию базы

**Comment by outsidious** [comment]
сделано: 
https://github.com/outsidious/del-meetups/pull/2/commits/f34a42c1dd6967cd1696f5053a5174f550c51848
